Capstone: com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter Class Reference
com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter Class Reference
Classes
class TabViewHolder
Add data here that will be relevant to tab logic, that can be accessed in onBindViewHolder(TabViewHolder, int) via the first argument.
Public Member Functions
TabViewPagerAdapter (Context context, IHostUIService uiService)
TabViewHolder onCreateViewHolder (@NonNull ViewGroup parent, int position)
void onBindViewHolder (@NonNull TabViewHolder holder, int position)
Main method that is called to initialize UI logic. It is called upon initialization, and all subsequent times the tab is changed.
int getItemCount ()
int getItemViewType (int position)
Constructor & Destructor Documentation
TabViewPagerAdapter()
com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.TabViewPagerAdapter (Context context, IHostUIService uiService)
Member Function Documentation
getItemCount()
int com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.getItemCount ()
References com.atakmap.android.trackingplugin.Constants.TAB_COUNT.
getItemViewType()
int com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.getItemViewType (int position)
onBindViewHolder()
void com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder (@NonNull TabViewHolder holder, int position)
Main method that is called to initialize UI logic. It is called upon initialization, and all subsequent times the tab is changed.
References com.atakmap.android.trackingplugin.DeviceStorageManager.clearList(), com.atakmap.android.trackingplugin.Constants.DEBUG_TABNAME, com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.discoverPluginContacts(), com.atakmap.android.trackingplugin.BluetoothReceiver.POLL_RATE_MILLIS, com.atakmap.android.trackingplugin.ui.SensorsTable.refreshData(), com.atakmap.android.trackingplugin.ui.SensorsTable.refreshUi(), com.atakmap.android.trackingplugin.Constants.SENSORS_TABNAME, com.atakmap.android.trackingplugin.plugin.TrackingPlugin.sensorsTable, com.atakmap.android.trackingplugin.ui.WhitelistTable.setup(), com.atakmap.android.trackingplugin.Constants.TAB_LAYOUTS, com.atakmap.android.trackingplugin.Constants.TRACKING_TABNAME, com.atakmap.android.trackingplugin.DeviceStorageManager.ListType.WHITELIST, com.atakmap.android.trackingplugin.Constants.WHITELIST_TABNAME, and com.atakmap.android.trackingplugin.plugin.TrackingPlugin.whitelistTable.
onCreateViewHolder()
TabViewHolder com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onCreateViewHolder (@NonNull ViewGroup parent, int position)
References com.atakmap.android.trackingplugin.Constants.TAB_LAYOUTS.
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/ui/TabViewPagerAdapter.java