Capstone: com.atakmap.android.trackingplugin.plugin.TrackingPlugin Class Reference
com.atakmap.android.trackingplugin.plugin.TrackingPlugin Class Reference
Public Member Functions
TrackingPlugin (IServiceController serviceController)
void onStart ()
void onStop ()
void showPane ()
Pass NULL to switch to main plugin pane.
Static Public Attributes
static final String TAG = Constants.createTag(TrackingPlugin.class)
static Pane primaryPane
static WhitelistTable whitelistTable
static SensorsTable sensorsTable
Constructor & Destructor Documentation
TrackingPlugin()
com.atakmap.android.trackingplugin.plugin.TrackingPlugin.TrackingPlugin (IServiceController serviceController)
References showPane(), and TAG.
Member Function Documentation
onStart()
void com.atakmap.android.trackingplugin.plugin.TrackingPlugin.onStart ()
References com.atakmap.android.trackingplugin.DeviceStorageManager.getDeviceList(), com.atakmap.android.trackingplugin.comms.DeviceCotListener.initialize(), TAG, com.atakmap.android.trackingplugin.ui.WhitelistTable.visibilityMap, and com.atakmap.android.trackingplugin.DeviceStorageManager.ListType.WHITELIST.
onStop()
void com.atakmap.android.trackingplugin.plugin.TrackingPlugin.onStop ()
References primaryPane, sensorsTable, TAG, com.atakmap.android.trackingplugin.comms.DeviceCotListener.uninitialize(), and whitelistTable.
showPane()
void com.atakmap.android.trackingplugin.plugin.TrackingPlugin.showPane ()
Pass NULL to switch to main plugin pane.
References primaryPane.
Referenced by TrackingPlugin().
Member Data Documentation
primaryPane
Pane com.atakmap.android.trackingplugin.plugin.TrackingPlugin.primaryPane static
Referenced by onStop(), com.atakmap.android.trackingplugin.ui.WhitelistTable.refreshTable(), com.atakmap.android.trackingplugin.ui.WhitelistTable.setup(), and showPane().
sensorsTable
SensorsTable com.atakmap.android.trackingplugin.plugin.TrackingPlugin.sensorsTable static
Referenced by com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder(), onStop(), and com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDiscoveryResponse().
TAG
final String com.atakmap.android.trackingplugin.plugin.TrackingPlugin.TAG = Constants.createTag(TrackingPlugin.class) static
Referenced by onStart(), onStop(), and TrackingPlugin().
whitelistTable
WhitelistTable com.atakmap.android.trackingplugin.plugin.TrackingPlugin.whitelistTable static
Referenced by com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder(), and onStop().
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/plugin/TrackingPlugin.java