Capstone: com.atakmap.android.trackingplugin.ui.SensorsTable Class Reference
com.atakmap.android.trackingplugin.ui.SensorsTable Class Reference
Public Member Functions
SensorsTable (View tabView)
void refreshUi ()
void addSensor (String name, String uid)
void refreshData ()
void onContactsSizeChange (Contacts contacts)
void onContactChanged (String uuid)
Constructor & Destructor Documentation
SensorsTable()
com.atakmap.android.trackingplugin.ui.SensorsTable.SensorsTable (View tabView)
Member Function Documentation
addSensor()
void com.atakmap.android.trackingplugin.ui.SensorsTable.addSensor (String name, String uid)
References refreshUi().
Referenced by com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDiscoveryResponse().
onContactChanged()
void com.atakmap.android.trackingplugin.ui.SensorsTable.onContactChanged (String uuid)
References refreshUi().
onContactsSizeChange()
void com.atakmap.android.trackingplugin.ui.SensorsTable.onContactsSizeChange (Contacts contacts)
refreshData()
void com.atakmap.android.trackingplugin.ui.SensorsTable.refreshData ()
References com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.discoverPluginContacts(), and refreshUi().
Referenced by com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder().
refreshUi()
void com.atakmap.android.trackingplugin.ui.SensorsTable.refreshUi ()
References com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendWhitelistRequest().
Referenced by addSensor(), com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder(), onContactChanged(), and refreshData().
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/ui/SensorsTable.java