Capstone: com.atakmap.android.trackingplugin.comms.DeviceCotListener Class Reference
com.atakmap.android.trackingplugin.comms.DeviceCotListener Class Reference
Public Member Functions
void onDeviceListChange (List< DeviceInfo > devices)
Static Public Member Functions
static void initialize ()
static void uninitialize ()
static Marker getMarkerByMacAddress (String macAddress)
static void setVisibility (String macAddress, boolean visible)
Static Public Attributes
static final MapGroup deviceGroup = MapView.getMapView().getRootGroup().addGroup("devices")
Member Function Documentation
getMarkerByMacAddress()
static Marker com.atakmap.android.trackingplugin.comms.DeviceCotListener.getMarkerByMacAddress (String macAddress) static
References deviceGroup.
initialize()
static void com.atakmap.android.trackingplugin.comms.DeviceCotListener.initialize () static
Referenced by com.atakmap.android.trackingplugin.plugin.TrackingPlugin.onStart().
onDeviceListChange()
void com.atakmap.android.trackingplugin.comms.DeviceCotListener.onDeviceListChange (List< DeviceInfo > devices)
Implements com.atakmap.android.trackingplugin.DeviceStorageManager.DeviceListChangeListener.
References deviceGroup.
setVisibility()
static void com.atakmap.android.trackingplugin.comms.DeviceCotListener.setVisibility (String macAddress, boolean visible) static
References deviceGroup.
Referenced by com.atakmap.android.trackingplugin.ui.WhitelistTable.refreshTable().
uninitialize()
static void com.atakmap.android.trackingplugin.comms.DeviceCotListener.uninitialize () static
Referenced by com.atakmap.android.trackingplugin.plugin.TrackingPlugin.onStop().
Member Data Documentation
deviceGroup
final MapGroup com.atakmap.android.trackingplugin.comms.DeviceCotListener.deviceGroup = MapView.getMapView().getRootGroup().addGroup("devices") static
Referenced by getMarkerByMacAddress(), onDeviceListChange(), and setVisibility().
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/comms/DeviceCotListener.java