ATAK Capstone: com.atakmap.android.trackingplugin.old.BluetoothTrackerService Class Reference
com.atakmap.android.trackingplugin.old.BluetoothTrackerService Class Reference
Public Member Functions
int onStartCommand (Intent intent, int flags, int startId)
void onCreate ()
void stopTracking ()
void onDestroy ()
IBinder onBind (Intent intent)
Static Public Member Functions
static Intent getServiceIntent (Context context)
Static Public Attributes
static final String DEVICE_FOUND = BluetoothTrackerService.class.getName() + ".DEVICE_FOUND"
Member Function Documentation
getServiceIntent()
static Intent com.atakmap.android.trackingplugin.old.BluetoothTrackerService.getServiceIntent (Context context) static
Allows activities to get an instance of the service. @removable @noinspection unused
onBind()
IBinder com.atakmap.android.trackingplugin.old.BluetoothTrackerService.onBind (Intent intent)
onCreate()
void com.atakmap.android.trackingplugin.old.BluetoothTrackerService.onCreate ()
References DEVICE_FOUND, and onCreate().
Referenced by onCreate().
onDestroy()
void com.atakmap.android.trackingplugin.old.BluetoothTrackerService.onDestroy ()
References onDestroy(), and stopTracking().
Referenced by onDestroy().
onStartCommand()
int com.atakmap.android.trackingplugin.old.BluetoothTrackerService.onStartCommand (Intent intent, int flags, int startId)
stopTracking()
void com.atakmap.android.trackingplugin.old.BluetoothTrackerService.stopTracking ()
References stopTracking().
Referenced by onDestroy(), and stopTracking().
Member Data Documentation
DEVICE_FOUND
final String com.atakmap.android.trackingplugin.old.BluetoothTrackerService.DEVICE_FOUND = BluetoothTrackerService.class.getName() + ".DEVICE_FOUND" static
Referenced by onCreate().
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/old/BluetoothTrackerService.java