Capstone: com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher Class Reference
com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher Class Reference
Static Public Member Functions
static void sendDeviceFound (DeviceInfo deviceInfo)
static void sendDeviceFound (Set< DeviceInfo > deviceInfoSet)
static void sendDeviceRemoval (DeviceInfo deviceInfo)
static void sendDeviceRemoval (Set< DeviceInfo > deviceInfoSet)
static void sendWhitelistRequest (String requestUid)
static void sendWhitelistResponse (String responseUid)
static void discoverPluginContacts (@Nullable String[] contactUids)
static void sendDiscoveryResponse (String requestUid)
Member Function Documentation
discoverPluginContacts()
static void com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.discoverPluginContacts (@Nullable String[] contactUids) static
Referenced by com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder(), and com.atakmap.android.trackingplugin.ui.SensorsTable.refreshData().
sendDeviceFound() [1/2]
static void com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDeviceFound (DeviceInfo deviceInfo) static
References com.atakmap.android.trackingplugin.DeviceInfo.macAddress, com.atakmap.android.trackingplugin.DeviceInfo.name, com.atakmap.android.trackingplugin.DeviceInfo.rssi, and com.atakmap.android.trackingplugin.DeviceInfo.sensorUid.
Referenced by com.atakmap.android.trackingplugin.BluetoothReceiver.onPoll(), and sendDeviceFound().
sendDeviceFound() [2/2]
static void com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDeviceFound (Set< DeviceInfo > deviceInfoSet) static
References sendDeviceFound().
sendDeviceRemoval() [1/2]
static void com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDeviceRemoval (DeviceInfo deviceInfo) static
References com.atakmap.android.trackingplugin.DeviceInfo.macAddress, and com.atakmap.android.trackingplugin.DeviceInfo.sensorUid.
Referenced by com.atakmap.android.trackingplugin.BluetoothReceiver.onPoll(), and sendDeviceRemoval().
sendDeviceRemoval() [2/2]
static void com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDeviceRemoval (Set< DeviceInfo > deviceInfoSet) static
References sendDeviceRemoval().
sendDiscoveryResponse()
static void com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDiscoveryResponse (String requestUid) static
References com.atakmap.android.trackingplugin.ui.SensorsTable.addSensor(), and com.atakmap.android.trackingplugin.plugin.TrackingPlugin.sensorsTable.
sendWhitelistRequest()
static void com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendWhitelistRequest (String requestUid) static
Referenced by com.atakmap.android.trackingplugin.ui.SensorsTable.refreshUi().
sendWhitelistResponse()
static void com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendWhitelistResponse (String responseUid) static
References com.atakmap.android.trackingplugin.DeviceStorageManager.getDeviceList(), and com.atakmap.android.trackingplugin.DeviceStorageManager.ListType.WHITELIST.
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/comms/DeviceCotDispatcher.java