Capstone: com.atakmap.android.trackingplugin.DeviceStorageManager Class Reference
com.atakmap.android.trackingplugin.DeviceStorageManager Class Reference
Class that handles persistent data involving lists of devices, primarily constructed for whitelist and sensor list.
Classes
interface DeviceListChangeListener
enum ListType
All valid lists that can be accessed.
Static Public Member Functions
static void addChangeListener (ListType listType, DeviceListChangeListener listener)
static List< DeviceInfo > getDeviceList (ListType listType)
static void addOrUpdateDevice (ListType listType, DeviceInfo deviceInfo)
static void removeDevice (ListType listType, String uuid)
static boolean containsDevice (ListType listType, String uuid)
static DeviceInfo getDevice (ListType listType, String uuid)
Returns device in the device list. If it isn't in the list, it will return null.
static Set< String > getUuids (ListType listType)
static String getUuid (ListType listType, String macAddress)
static void clearList (ListType listType)
Detailed Description
Class that handles persistent data involving lists of devices, primarily constructed for whitelist and sensor list.
Member Function Documentation
addChangeListener()
static void com.atakmap.android.trackingplugin.DeviceStorageManager.addChangeListener (ListType listType, DeviceListChangeListener listener) static
Referenced by com.atakmap.android.trackingplugin.BluetoothReceiver.BluetoothReceiver(), and com.atakmap.android.trackingplugin.ui.WhitelistTable.WhitelistTable().
addOrUpdateDevice()
static void com.atakmap.android.trackingplugin.DeviceStorageManager.addOrUpdateDevice (ListType listType, DeviceInfo deviceInfo) static
If DeviceInfo was constructed with UUID as "null", a new entry will be created. If UUID was supplied when constructing DeviceInfo, the entry with that UUID will be overwritten.
References com.atakmap.android.trackingplugin.DeviceInfo.uuid.
clearList()
static void com.atakmap.android.trackingplugin.DeviceStorageManager.clearList (ListType listType) static
Referenced by com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder().
containsDevice()
static boolean com.atakmap.android.trackingplugin.DeviceStorageManager.containsDevice (ListType listType, String uuid) static
getDevice()
static DeviceInfo com.atakmap.android.trackingplugin.DeviceStorageManager.getDevice (ListType listType, String uuid) static
Returns device in the device list. If it isn't in the list, it will return null.
Referenced by com.atakmap.android.trackingplugin.ui.WhitelistTable.refreshTable().
getDeviceList()
static List< DeviceInfo > com.atakmap.android.trackingplugin.DeviceStorageManager.getDeviceList (ListType listType) static
Referenced by com.atakmap.android.trackingplugin.BluetoothReceiver.BluetoothReceiver(), com.atakmap.android.trackingplugin.plugin.TrackingPlugin.onStart(), and com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendWhitelistResponse().
getUuid()
static String com.atakmap.android.trackingplugin.DeviceStorageManager.getUuid (ListType listType, String macAddress) static
References com.atakmap.android.trackingplugin.DeviceInfo.macAddress.
getUuids()
static Set< String > com.atakmap.android.trackingplugin.DeviceStorageManager.getUuids (ListType listType) static
Referenced by com.atakmap.android.trackingplugin.ui.WhitelistTable.refreshTable().
removeDevice()
static void com.atakmap.android.trackingplugin.DeviceStorageManager.removeDevice (ListType listType, String uuid) static
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/DeviceStorageManager.java