Capstone: com.atakmap.android.trackingplugin.ui.WhitelistTable Class Reference
com.atakmap.android.trackingplugin.ui.WhitelistTable Class Reference
Public Member Functions
WhitelistTable (IHostUIService uiService, View tabView)
void setup ()
void refreshTable ()
void setAddDeviceFieldValidators (String defaultName, String defaultMacAddress, EditText nameField, EditText macAddressField)
void onDeviceListChange (List< DeviceInfo > devices)
Static Public Attributes
static final Map< String, Boolean > visibilityMap = new HashMap<>()
Constructor & Destructor Documentation
WhitelistTable()
com.atakmap.android.trackingplugin.ui.WhitelistTable.WhitelistTable (IHostUIService uiService, View tabView)
References com.atakmap.android.trackingplugin.DeviceStorageManager.addChangeListener(), and com.atakmap.android.trackingplugin.DeviceStorageManager.ListType.WHITELIST.
Member Function Documentation
onDeviceListChange()
void com.atakmap.android.trackingplugin.ui.WhitelistTable.onDeviceListChange (List< DeviceInfo > devices)
Implements com.atakmap.android.trackingplugin.DeviceStorageManager.DeviceListChangeListener.
References refreshTable().
refreshTable()
void com.atakmap.android.trackingplugin.ui.WhitelistTable.refreshTable ()
References com.atakmap.android.trackingplugin.DeviceStorageManager.getDevice(), com.atakmap.android.trackingplugin.DeviceStorageManager.getUuids(), com.atakmap.android.trackingplugin.DeviceInfo.macAddress, com.atakmap.android.trackingplugin.DeviceInfo.name, com.atakmap.android.trackingplugin.plugin.TrackingPlugin.primaryPane, com.atakmap.android.trackingplugin.comms.DeviceCotListener.setVisibility(), com.atakmap.android.trackingplugin.DeviceInfo.uuid, visibilityMap, and com.atakmap.android.trackingplugin.DeviceStorageManager.ListType.WHITELIST.
Referenced by onDeviceListChange(), and setup().
setAddDeviceFieldValidators()
void com.atakmap.android.trackingplugin.ui.WhitelistTable.setAddDeviceFieldValidators (String defaultName, String defaultMacAddress, EditText nameField, EditText macAddressField)
setup()
void com.atakmap.android.trackingplugin.ui.WhitelistTable.setup ()
References com.atakmap.android.trackingplugin.plugin.TrackingPlugin.primaryPane, and refreshTable().
Referenced by com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder().
Member Data Documentation
visibilityMap
final Map<String, Boolean> com.atakmap.android.trackingplugin.ui.WhitelistTable.visibilityMap = new HashMap<>() static
Referenced by com.atakmap.android.trackingplugin.plugin.TrackingPlugin.onStart(), and refreshTable().
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/ui/WhitelistTable.java