Capstone: com.atakmap.android.trackingplugin.BluetoothReceiver Class Reference
com.atakmap.android.trackingplugin.BluetoothReceiver Class Reference
Classes
class ACTIONS
Class made for grouping all the actions that can be registered for BluetoothReceiver.
Public Member Functions
BluetoothReceiver (Context context)
void onReceive (Context context, Intent intent)
void onPoll ()
void onDeviceListChange (List< DeviceInfo > devices)
Static Public Member Functions
static boolean hasAllBtPermissions (Context context)
Static Public Attributes
static int POLL_RATE_MILLIS = 5000
static final Map< String, DeviceInfo > lastIntervalDevices = Collections.synchronizedMap(new HashMap<>())
static final Map< String, DeviceInfo > currentIntervalDevices = Collections.synchronizedMap(new HashMap<>())
Detailed Description
BluetoothReceiver handles all the logic between a bluetooth scan and info retrieval from said scans. This is particularly true for Bluetooth LE scans.
Constructor & Destructor Documentation
BluetoothReceiver()
com.atakmap.android.trackingplugin.BluetoothReceiver.BluetoothReceiver (Context context)
Parameters
context Context for overall plugin.
References com.atakmap.android.trackingplugin.DeviceStorageManager.addChangeListener(), com.atakmap.android.trackingplugin.DeviceStorageManager.getDeviceList(), onDeviceListChange(), and com.atakmap.android.trackingplugin.DeviceStorageManager.ListType.WHITELIST.
Member Function Documentation
hasAllBtPermissions()
static boolean com.atakmap.android.trackingplugin.BluetoothReceiver.hasAllBtPermissions (Context context) static
Referenced by onReceive().
onDeviceListChange()
void com.atakmap.android.trackingplugin.BluetoothReceiver.onDeviceListChange (List< DeviceInfo > devices)
Implements com.atakmap.android.trackingplugin.DeviceStorageManager.DeviceListChangeListener.
Referenced by BluetoothReceiver().
onPoll()
void com.atakmap.android.trackingplugin.BluetoothReceiver.onPoll ()
References currentIntervalDevices, lastIntervalDevices, com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDeviceFound(), and com.atakmap.android.trackingplugin.comms.DeviceCotDispatcher.sendDeviceRemoval().
onReceive()
void com.atakmap.android.trackingplugin.BluetoothReceiver.onReceive (Context context, Intent intent)
References hasAllBtPermissions().
Member Data Documentation
currentIntervalDevices
final Map<String, DeviceInfo> com.atakmap.android.trackingplugin.BluetoothReceiver.currentIntervalDevices = Collections.synchronizedMap(new HashMap<>()) static
Referenced by onPoll().
lastIntervalDevices
final Map<String, DeviceInfo> com.atakmap.android.trackingplugin.BluetoothReceiver.lastIntervalDevices = Collections.synchronizedMap(new HashMap<>()) static
Referenced by onPoll().
POLL_RATE_MILLIS
int com.atakmap.android.trackingplugin.BluetoothReceiver.POLL_RATE_MILLIS = 5000 static
Referenced by com.atakmap.android.trackingplugin.ui.TabViewPagerAdapter.onBindViewHolder().
The documentation for this class was generated from the following file:
app/src/main/java/com/atakmap/android/trackingplugin/BluetoothReceiver.java