name: Run JUnit Tests for ATAK Plugin

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - ui-dev
      - bt-dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle  # Enables caching for Gradle dependencies

      - name: Grant execute permissions to Gradle
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 7.5.1

      - name: Run Unit Tests
        run: ./gradlew test --info --stacktrace

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: build/reports/tests/
