# This file is our workflows. It takes the sdk from a public git repo release
name: Build & Test ATAK Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android tools
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9862592

      - name: Install Android SDK 33 and Build Tools 30.0.3
        run: |
          sdkmanager "platforms;android-33" "build-tools;30.0.3"
          yes | sdkmanager --licenses

      - name: Prepare ATAK SDK environment
        run: |
          curl -L \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.SDK_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -o ATAK-CIV-SDK.zip \
            https://api.github.com/repos/lith-x/tak-sdk/releases/assets/243330334
          unzip ATAK-CIV-SDK.zip -d .
          mkdir -p ATAK-CIV-5.4.0.1-SDK/plugins/Capstone-project

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'ATAK-CIV-5.4.0.1-SDK/plugins/Capstone-project'

      - name: Grant execute permissions to Gradle
        run: chmod +x gradlew
        working-directory: 'ATAK-CIV-5.4.0.1-SDK/plugins/Capstone-project'

      - name: Build Debug
        run: ./gradlew assembleCivDebug
        working-directory: 'ATAK-CIV-5.4.0.1-SDK/plugins/Capstone-project'

      - name: Run Debug Unit Tests
        run: ./gradlew testCivDebugUnitTest
        working-directory: 'ATAK-CIV-5.4.0.1-SDK/plugins/Capstone-project'

#      - name: Build Release
#        run: ./gradlew assembleCivRelease
#        working-directory: 'ATAK-CIV-5.4.0.1-SDK/plugins/Capstone-project'

#      - name: Run Release Unit Tests
#        run: ./gradlew testCivReleaseUnitTest
#        working-directory: 'ATAK-CIV-5.4.0.1-SDK/plugins/Capstone-project'