#This file is our workflows. It takes the sdk from a public git repo release
name: Build & Test ATAK Plugin

on:
  push:
    branches:
      - main
      - TrapperTesting
  pull_request:
    branches:
      - main
      - TrapperTesting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download ATAK SDK from GitHub Release
        run: |
          curl -L \
            -o ATAK-CIV-5.3.0.12-SDK-Zip.zip \
            https://github.com/trafryda/ATAKSDK/releases/download/v1.0.0/ATAK-CIV-5.3.0.12-SDK-Zip.zip
          unzip ATAK-CIV-5.3.0.12-SDK-Zip.zip -d ATAK-CIV-5.3.0.12-SDK

      - name: Grant execute permissions to Gradle
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build --info --stacktrace
